# Generated by Django 5.1.2 on 2024-11-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_hotel_description_en_hotel_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
