# Generated by Django 5.1.2 on 2024-11-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_hotel_hotel_name_alter_hotel_hotel_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.CharField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=16, null=True),
        ),
    ]
