# Generated by Django 5.1.2 on 2024-11-05 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_review_parent_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='start',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
