# Generated by Django 5.1.2 on 2024-11-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_hotel_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='room name', max_length=32),
        ),
    ]
