# Generated by Django 5.1.2 on 2024-11-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
    ]
